import Head from 'next/head'
import Header from '../components/Header'
import Training from '../components/Training'

export default function Home() {
  return (
    <div className="overflow-y-hidden">
      <Head>
        <title>Road to TheRock le Boss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/#" />
      </Head>

      <Header />
      <Training />
     
    </div>
  )
}
